### ISSUE TITLE
无论鼠标是否移动总是触发MoveEvent这个问题有解决方案吗

### ISSUE THREAD

**Issue by shaozhihua** [Mud-Player/GraphicsMapLib#4]
如题。

**Comment by Mud-Player** [comment]
> 如题。
抱歉，挺久没有做Qt开发了，您试试setMouseTracking(bool)，这个接口可以控制是触发MouseMoveEvent事件

**Comment by shaozhihua** [comment]
我记得setMouseTracking是控制鼠标的移动事件的触发是否需要按住鼠标左键，不过当我在InteractiveMap的构造中加上setMouseTracking(false);语句后它确实解决了问题，当在view中仅仅点击一下鼠标，不会再触发MouseMoveEvent()了。看来我还需要再理解一下这个函数。
